version: "3"
services:
  app:

    image: node:19 
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - db 

  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: dbpasteleria
      POSTGRES_USER: pasteleria
      POSTGRES_PASSWORD: pasteleria1.
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: 
